# Generated by Django 4.2.6 on 2024-06-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_album_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='liked_by',
            new_name='disliked_by',
        ),
    ]
