# Generated by Django 4.2.6 on 2024-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_liked_by_dislike_disliked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='rec',
            field=models.FileField(null=True, upload_to='music'),
        ),
        migrations.AddField(
            model_name='track',
            name='streams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
